### ISSUE TITLE
Add Mekanism 8 support, it crashes now

### ISSUE THREAD

**Issue by erkro1** [joshiejack/ModTweaker#90]
Like this problem is caused because ModTweaker doesn't support Mekanism 8, could you fix it?
https://github.com/aidancbrady/Mekanism/issues/2459

This issue if very annoying because it crashes when you lookup a recipe by left clicking or pressing R.

**Comment by Yulife** [comment]
Wrong repo, mate. This was already reported.

**Comment by accessdenied0** [comment]
Dear @Yulife ,

do you have the reference handy? Is it allready recognized... this issue isn't very new... If the mod author is busy, than isn't a problem, but I'm not able to update until this issue is fixed... so a simple recolonization from the mod author would be nice...

wishes,

access_denied

**Comment by Yulife** [comment]
Look at the recent issue on the new repo.

**Comment by accessdenied0** [comment]
Dear @Yulife ,

You are not very clear...
I guess you mean this one: https://github.com/jaredlll08/ModTweaker2/issues/105 ?

I'm not sure because there are 4 different projects...
https://github.com/joshiejack/ModTweaker/
https://github.com/jaredlll08/Mod-Tweaker2/
https://github.com/jaredlll08/ModTweaker2/
https://github.com/jaredlll08/ModTweaker2-Documentation/

I do guess the last-one has nothing to do with issues (or this besides it is empty) and the first one (this one) is the old ModTweaker and maybe not longer supported. I searched through the left two and the only one I could find and which could fit this issue was, how I said, this one: https://github.com/jaredlll08/ModTweaker2/issues/105

Thanks for help,

access_denied

**Comment by Yulife** [comment]
Haha, with 4 repos of course confusion gets created.
** https://github.com/joshiejack/ModTweaker/ **:
Old repo of joshiejack, please ignore and don't use.
** https://github.com/jaredlll08/Mod-Tweaker2/ **:
A highly WIP, **rewritten** Modtweaker with the postfix of 2. Not out yet.
** https://github.com/jaredlll08/ModTweaker2/ **:
The continued repo of Modtweaker1 (dont get confused by the 2) by jared, just some bugfixes and is on Curseforge.
** https://github.com/jaredlll08/ModTweaker2-Documentation/ **:
Due to the rewrite a lot of re-documenting is needed. Thus, mainly me and a few other people will post documenting pages on there.
